server:
  port: 10086
spring:
  application:
    name: ly-registry

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10086/eureka/
  server:
    #开启自我保护
    enable-self-preservation: false
    #拉去微服务的时间
    eviction-interval-timer-in-ms: 5000