server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://47.99.73.15:3306/leyou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  application:
    name: user-service
  profiles:
    active: dev
  rabbitmq:
    host: 47.99.73.15
  redis:
    host: 47.99.73.15
eureka:
  client:
    service-url:
      defaultZone: http://47.100.48.207:10086/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #type-enums-package: com.leyou.service.pojo.enums
  configuration:
    map-underscore-to-camel-case: true
ly:
  mq:
    smsExchange: ly.sms.exchange
    smsVerityRoutingKey: ly.sms.verity