spring:
  application:
    name: upload-service
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://47.100.48.207:10086/eureka/
    #每多少秒获取服务列表
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    #默认以ip优先  而不是主机名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #eureka 服务查找周期
    lease-expiration-duration-in-seconds: 10 #eureka 服务过期时间
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.100.48.207:22122

filePrefix: http://47.100.48.207:8888/