server:
  port: 8084
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://47.100.48.207:10086/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}.${server.port}
static:
  html:
    url: D:\nginx-1.12.2\html