server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.99.73.15:3306/leyou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  application:
    name: item-service
  profiles:
    active: dev

  rabbitmq:
    host: 47.99.73.15
    #消息确认
    publisher-confirms: true
    template:
      exchange: ly.item.exchange
      #失败重试
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2

eureka:
  client:
    service-url:
      defaultZone: http://47.100.48.207:10086/eureka/
    #每多少秒获取服务列表
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    #默认以ip优先  而不是主机名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #eureka 服务查找周期
    lease-expiration-duration-in-seconds: 10 #eureka 服务过期时间
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-enums-package: com.leyou.service.pojo.enums
  configuration:
    map-underscore-to-camel-case: true #驼峰转下划线